export enum DropDownTypes {
    "Specialization" = 1,
    "Religion" = 2,
    "Official Task Request" = 3,
    "Nationality" = 4,
    "Media Channel" = 5,
    "Location" = 6,
    "Languages" = 7,
    "Experience" = 8,
    "Employee Status" = 9,
    "Emirates" = 10,
    "Education" = 11,
    "Design Type" = 12,
    "Country" = 13,
    "City" = 14,
    "Meeting Type" = 16,
    "Leave Type" = 17,
    "Trip Type" = 18,
    "Vehicle Model" = 19,
    "Announcement Type" = 20,
    "Announcement Description" = 21
}
