import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ArabicDataService {
  constructor() { }
  globalsearch = {
    'memos': 'المذكرات',
    'letters': 'الكتب',
    'dutytask': 'المهام',
    'meetings': 'اجتماعات',
    'circulars': 'التعاميم',
    'protocol': 'المراسم',
    'legal': 'الدعم القانوني',
    'it': 'تقنية المعلومات​',
    'hr': 'الموارد البشرية',
    'maintenance': 'خدمات الصيانة',
    'citizenaffair': 'شؤون المواطنين'
  };
  sideNavArabic = {
    'memos': 'المذكرات',
    'Pending Memo List': 'قائمة المذكرات المعلقة ',
    'Incoming Memos': 'المذكرات الواردة',
    'Outgoing Memos': 'المذكرات الصادرة',
    'Draft Memos': 'مسودات المذكرات',
    'Historical Memos Incoming': 'سجلات المذكرات الواردة السابقة',
    'Historical Memos Outgoing': 'سجلات المذكرات الصادرة السابقة',
    'circular': 'التعاميم الإدارية',
    'My Pending Circulars': 'التعاميم المعلقة',
    'Incoming Circulars': 'التعاميم الواردة',
    'Outgoing Circulars': 'التعاميم الصادرة',
    'Draft Circulars': 'مسودة التعاميم',
    'Create Task': 'إنشاء مهمة',
    'Duty Task': 'المهام',
    'Dashboard': 'لوحة المعلومات',
    'Task Dashboard': 'لوحة المعلومات',
    'My Task': 'مهامي',
    'Assigned Task': 'المهام المسندة',
    'Participants': 'المهام المشاركة',
    'taskparticipants': 'المهام المشارك بها',
    'My Pending Actions Incoming': 'الوارد - بحاجة للإطلاع',
    'My Pending Actions Outgoing': 'الصادر - بحاجة للإطلاع',
    'Incoming Letters': 'الكتب الواردة',
    'Outgoing Letters': 'الكتب الصادرة',
    'Draft Letters': 'مسودة الكتب',
    'Historical Letters': 'الكتب المؤرشفة',
    'letters': 'الكتب',
    'Meetings': 'اجتماعات',
    'My Calendar': 'جدول اجتماعاتي',
    'Meeting List': 'قائمة الاجتماعات',
    'Create Meeting': 'إنشاء اجتماع'
  };



  words = {
    'legal': 'الدعم القانوني',
    'legalrequestview': 'عرض الطلبات',
    'PrintReleaseForm': 'طباعة نموذج التسليم',
    'PrintReturnForm': 'طباعة نموذج الإستعادة',
    'letters': 'رسالة',
    'lettersentsuccess': 'تم إرسال الكتاب بنجاح',
    'lettersavesuccess': 'تم حفظ مسودة الكتاب بنجاح.',
    'letteroutgoinredirected': 'تمت إعادة توجيه الكتاب الصادر بنجاح',
    'letteroutgoingescalated': 'تم رفع الكتاب الصادر للاعتماد بنجاح',
    'letterrejected': 'تم رفض الكتاب بنجاح',
    'letterredirectedby': 'إعادة توجيه بواسطة',
    'letterrejectdby': 'رفض من قبل',
    'lettersubmittedby': 'قدم بواسطة',
    'letterresubmittedby': 'مقدم من:',
    'public': 'عامة',
    'restricted': 'داخلي',
    'confidential': 'سري',
    'secret': 'سري للغاية',
    'circularresubmitsuccess': 'تمت إعادة تقديم التعميم الإداري بنجاح',
    'circularsubmitsuccess': 'تم إرسال التعميم الإداري بنجاح',
    'circulardeletedsuccess': 'تم حذف التعميم بنجاح',
    'circularclonesuccess': 'تم نسخ التعميم الإداري بنجاح',
    'circularapprovesuccess': 'تم التعميم بنجاح',
    'circularrejectsuccess': 'تم رفض التعميم بنجاح',
    'circularclosedsuccess': 'التعميم مغلق بنجاح',
    'circularupdatesuccess': 'تم تحديث التعميم بنجاح',
    'circulardraftsuccess': 'تم حفظ مسودة التعميم بنجاح',
    'circularcloneby': 'تم النسخ من قبل',
    'circularsaveby': 'حفظ بواسطة',
    'circularsubmitby': 'مقدم من',
    'circularresubmitby': 'مقدم من',
    'circularrejectby': 'مرفوض من قبل',
    'circularescalateby': 'رفع للموافقة من قبل',
    'circularreturnforinfoby': 'إرجاع لمزيد من المعلومات',
    'createMaintenanceRequest': 'انشاء طلب صيانة',
    'viewMaintenanceRequest': 'عرض طلب الصيانة',
    'internalmemos': 'المذكرات الداخلية',
    'list': 'قائمة',
    'memolist': 'قائمة المذكرات',
    'status': 'الحالة',
    'destinationou': 'مرسلة إلى',
    'sourceofficeSlashDepartment': 'صادرة عن (مكتب / إدارة)',
    'sourceofficedepartment': 'صادرة عن (مكتب / إدارة)',
    'destinationoffice/department': 'الوجهة (مكتب / إدارة)',
    'destinationusername': 'اسم المستلم',
    'organizeroffice/department': 'مكتب/ إدارة منظم الإجتماع',
    'office/department': 'المكتب / الإدارة',
    'approverofficeSlashDepartment': 'للإعتماد من (مكتب / إدارة)',
    'approverofficedepartment': 'للإعتماد من (مكتب / إدارة)',
    'assigneeofficeSlashDepartment': 'مكتب / إدارة المكلف',
    'participantOfficeSlashDepartment': 'مكتب / إدارة المشاركين',
    'requestorofficeSlashDepartment': 'مكتب الطالب / القسم',
    'doaoffice/department': 'مكتب دعاء / قسم',
    'doaofficedepartment': 'تفويض (مكتب / إدارة)',
    'placeholderdoaofficedepartment': 'الرجاء اختيار مكتب أو قسم الموظف المراد تفويضه',
    'employeeofficeSlashDepartment': 'مكتب/ إدارة الموظف',
    'personoffice/department': 'مكتب شخص / قسم',
    'taskparticipants': 'المهام المشارك بها',
    'dateto': 'تاريخ ل',
    'private': 'المشاركة مع الزملاء؟',
    'priority': 'الأولويات',
    'smartsearch': 'البحث الذكي',
    'refid': 'الرقم المرجعي',
    'title': 'الموضوع',
    'tasktitle': 'موضوع المهمة',
    'listviewtasktitle': 'عنوان المهمة',
    'circulartitle': 'العنوان',
    'source': 'المصدر',
    'destination': 'الوجهة',
    'date': 'تاريخ',
    'userprofiledate': 'التاريخ',
    'joindate': 'تاريخ التوظيف',
    'action': 'عرض',
    'search': 'بحث',
    'showavailablereports': 'عرض التقارير المتاحة',
    'all': 'الكل',
    'underprogress': 'تحت الاجراء',
    'closed': 'تمت',
    'waitingforapproval': 'قيد الاعتماد',
    'rejected': 'مرفوضة',
    'returnforinfoby': 'إرجاع لمزيد من المعلومات',
    'pendingforresubmission': 'في انتظار إعادة التقديم',
    'draft': 'مسودة',
    'high': 'فائق الأهمية',
    'medium': 'متوسط الأهمية',
    'low': 'منخفض الأهمية',
    'verylow': 'غير مهم',
    'report': 'تقارير',
    'downloadexcel': 'تحميل اكسل',
    'yes': 'نعم',
    'no': 'لا',
    'both': 'كلاهما',
    'memocreate': 'انشاء مذكرة',
    'memotitle': 'موضوع المذكرة',
    'username': 'اسم المستخدم',
    'destinationname': 'اسم المرسل إليه (الوجهة)',
    'approvebydepartment': 'للاعتماد من قسم',
    'approvebyname': 'للاعتماد من قبل',
    'details': 'التفاصيل',
    'attachments': 'المرفقات', // this is the crct text for attachments
    'keywords': 'كلمات البحث',
    'send': 'إرسال',
    'saveasdraft': 'حفظ كمسودة',
    'print/preview': 'عرض / طباعة',
    'printpreview': 'عرض / طباعة',
    'print': 'طباعة',
    'attachmentlist': 'قائمة المرفقات',
    'filename': 'اسم الملف',
    'fileUpSuc': 'تم رفع الملف بنجاح',
    'uploadedDate': 'تاريخ التحميل',
    'deleteFile': 'حذف ملف',
    'deletethisfile': 'هل تريد حقًا حذف هذا الملف',
    'delConfMsg': 'هل تريد حقًا حذف هذا الملف',
    'success': 'نجاح',
    'ok': 'حسنا',
    'referenceid': 'الرقم المرجعي',
    'creationdate': 'تاريخ الإنشاء',
    'sourcename': 'صادرة عن',
    'comments': 'الملاحظات',
    'approve': 'اعتماد',
    'reject': 'رفض',
    'escalate': 'رفع للاعتماد',
    'mediaescalatebtn': 'رفع للموافقة',
    'returnforinfo': 'طلب تعديل أو معلومة',
    'redirect': 'اعادة توجيه',
    'submittedby': 'أنشئ بواسطة ',
    'clonedby': 'نسخت بواسطة',
    'Clonedby': 'نسخت بواسطة',
    'department': 'القسم',
    'user': 'المستخدم',
    'close': 'اغلاق',
    'save': 'حفظ',
    'validids': 'الوثائق',
    'escalatedby': 'رفع للاعتماد بواسطة',
    'memoescalatedby': 'رفع للاعتماد بواسطة',
    'Escalated': 'رفعت للاعتماد بواسطة',
    'redirectedby': 'تم التوجيه من قبل',
    'sharememo': 'مشاركة مذكرة',
    'sharedby': 'تمت المشاركة بواسطة',
    'approvedby': 'تم اعتماده من قبل ',
    'clone': 'نسخ',
    'closedby': 'أغلق بواسطة',
    'Closedby': 'أغلق بواسطة',
    'downloadaspdf': 'تنزيل ملف بي دي إف',
    'delete': 'حذف',
    'addnew': 'إضافة جديد',
    'submitted': 'قدمت',
    'memoSubmitted': 'تم الإنشاء بواسطة',
    'memoSaved': 'حفظ بواسطة',
    'memoredirected': 'تم إعادة التوجيه بواسطة',
    'memoEscalated': 'تم بالفعل تقديم المذكرة للموافقة عليها ملاحظات',
    'leaverequests': 'طلب إجازة',
    'certificateto': 'اسم المعني',
    'salarycertificate': 'طلب شهادة راتب',
    'salarycertificatecreation': 'إنشاء شهادة راتب',
    'salarycertificateview': 'عرض طلبات شهادات الراتب',
    'salarysubmittedby': 'مقدم من',
    'salaryassignedby': 'أسند من',
    'salaryclosedby': 'أغلق بواسطة',
    'salaryassignto': 'إسناد إلى',
    'experiencecertificate': 'طلب شهادة خبرة',
    'experiencecertificatecreation': 'انشاء طلب شهادة خبرة',
    'experiencecertificateview': 'عرض طلبات شهادات الخبرة',
    'experiencesubmittedby': 'مقدم من',
    'experienceassignedby': 'أسند من قبل',
    'experienceclosedby': 'أغلق',
    'newbabyaddition': 'طلب إضافة طفل جديد',
    'babyadditionassignedby': 'أسند من قبل',
    'newbabysourceou': 'صادرة عن',
    'newbabysourcename': 'اسم المصدر',
    'announcementassignto': 'يسند إلى',
    'announcementassignedby': 'أسند بواسطة',
    'announcementassignedsuccess': 'تم إسناد طلب الإعلان بنجاح',
    'announcementclosedsuccess': 'تم إغلاق طلب الإعلان بنجاح',
    'announcementrequests': 'طلب إعلان',
    'announcementtype': 'نوع الإعلان المطلوب',
    'announcementdescription': 'وصف الإعلان',
    'officialrequests': 'طلبات المهام الرسمية',
    'emphasanothertask': 'الموظف لديه مهمة رسمية أخرى خلال نفس الفترة',
    'trainingrequests': 'طلب دورة تدريبية',
    'raisecomplaintssuggestions': 'طلب الشكاوي / والاقتراحات',
    'raisecomplaintsandsuggestions': 'رفع الشكاوى والاقتراحات',
    'cvbank': 'بنك السير الذاتية',
    'cvbanklist': 'بنك السير الذاتية',
    'createcv': 'إنشاء السيرة الذاتية',
    'viewcv': 'عرض السيرة الذاتية',
    'candidatename': 'اسم المرشح',
    'emailhipenid': 'عنوان الإيميل',
    'educationqualification': 'المؤهل العلمي',
    'yeasofexperience': 'سنوات الخبرة',
    'areaofexpertice': 'مجال الخبرة',
    'address': 'عنوان',
    'uploadcv': 'تحميل السيرة الذاتية',
    'position': 'المنصب',
    'cvdateto': 'تاريخ ل',
    'cvrecordsubmittedsuccess': 'تم إدخال السيرة الذاتية بنجاح',
    'employeeprofile': 'ملفات تعريف الموظفين',
    'employeesprofilelist': 'قائمة ملفات تعريف الموظفين',
    'hrdocuments': 'وثائق الموارد البشرية',
    'filterby': 'تصفية بواسطة',
    'requestdateto': 'تاريخ الطلب إلى',
    'requestdatefrom': 'تاريخ الطلب من',
    'requesttype': 'نوع الطلب',
    'creator': 'منشئ المهمة',
    'mypendingrequests': 'طلباتي المعلقة',
    'myprocessedrequest': 'الطلبات المنجزة بواسطتي',
    'myownrequests': 'طلباتي الخاصة',
    'participantdepartment': 'قسم المشاركين',
    'participantname': 'أسماء المشاركين',
    'remindmeat': 'ذكرني في',
    'linktomemo': 'ارتباط بمذكرة',
    'lintoletter': 'ارتباط بكتاب',
    'label': 'الكلمات البحثية',
    'complete': 'اكتملت',
    'submit': 'إرسال',
    'mediasubmitbtn': 'إرسال',
    'assigneename': 'إسم المكلف',
    'assigneedepartment': 'الإدارة المكلفة',
    'duedate': 'تاريخ التنفيذ',
    'remindermeon': 'تاريخ التذكير',
    'startdate': 'تاريخ البدء',
    'createdate': 'تاريخ الإنشاء',
    'taskid': 'رقم المهمة',
    'daterangefrom': 'التاريخ - من',
    'daterangeto': 'التاريخ - إلى',
    'sendername': 'اسم المرسل',
    'issuedelivernote': 'إصدار مذكرة تسليم',
    'linkedtootherletter': 'الربط مع كتاب اخر',
    'replied': 'بحاجة لرد',
    'outgoingcreation': 'إنشاء كتاب صادر',
    'letterref': 'رقم الكتاب المرجعي',
    'lettertittle': 'موضوع الكتاب',
    'destinationentity': 'جهة الاستلام',
    'name': 'الاسم',
    'addanotherrecipientbulkcreation': 'إضافة مستلم اخر (إنشاء جماعي) +',
    'approverdepartment': 'معتمد من قسم',
    'approvername': 'الاعتماد - الاسم',
    'selectapprovername': 'اختر اسم المخول بالاعتماد',
    'relatedtooutgoingletters': 'مرتبط بكتاب صادر',
    'relatedtoincomingletters': 'مرتبط بكتاب وارد',
    'letterlinkmessage': 'الرقم المرجعي غير صالح أو لا يمكنك الوصول إلى هذا الرقم المرجعي',
    'letterdetails': 'تفاصيل الكتاب',
    'documentclassification': 'تصنيف الكتاب',
    'needreply': 'بحاجة لرد',
    'approvesendtodestination': 'معتمد (تم الارسال للوجهة)',
    'download': 'تنزيل الملف',
    'referencenumber': 'الرقم المرجعي',
    'employer': 'صاحب العمل',
    'CAemployer': 'جهة العمل',
    'monthlysalary': 'الراتب الشهري',
    'emiratesid': 'الهوية الإماراتية',
    'martialstatus': 'الحالة الاجتماعية',
    'noofchildren': 'عدد الأطفال',
    'phonenumber': 'رقم الهاتف',
    'mobileno': 'رقم الهاتف المتحرك',
    'employeephoneno': 'رقم الهاتف الأرضي',
    'religion': 'الديانة',
    'nationality': 'الجنسية',
    'resigned': 'تمت الاستقالة؟',
    'employeeposition': 'المنصب الوظيفي',
    'notificationpreference': 'تفضيلات الإخطارات',
    'employmentstatus': 'الحالة الوظيفية',
    'resignationdate': 'تاريخ الاستقالة',
    'previousnationality': 'الجنسية السابقة',
    'workexperience': 'الخبرة العملية',
    'emirates': 'الإمارة',
    'taskemirates': 'الإمارة',
    'city': 'المدينة',
    'age': 'العمر',
    'reportobjectives': 'أهداف التقرير',
    'findingnotes': 'الملاحظات والنتائج',
    'recommendation': 'التوصيات',
    'location': 'الموقع',
    'requestby': 'طلب مقدم من',
    'visitobjectives': 'هدف الزيارة',
    'forwhom': 'لمن',
    'personal': 'تقرير شخصي',
    'passportno': 'رقم جواز السفر',
    'passportissueplace': 'مكان إصدار جواز سفر',
    'passportissuedate': 'تاريخ إصدار جواز السفر',
    'locationname': 'اسم الموقع',
    'attachdocument': 'أرفق الوثيقة (الوثائق)',
    'attachphoto': 'إرفاق الصور',
    'notifyuponapproval': 'إشعار عند الموافقة',
    'internalrequestor': 'طلب داخلي',
    'person-department': 'القسم',
    'person-name': 'الاسم',
    'externalrequestor': 'طلب من جهة خارجية',
    'emailid': 'البريد الالكتروني',
    'email': 'البريد الإلكتروني',
    'sms': 'رسالة قصيرة',
    'education': 'المؤهل العلمي',
    'degree': 'الدرجة العلمية',
    'schoolcollege': 'مدرسة / كلية',
    'fieldofstudy': 'مجال الدراسة',
    'timeperiodfrom': 'الفترة الزمنية من',
    'timeperiodto': 'الفترة الزمنية إلى',
    'from': 'من',
    'trainingscertificatons': 'الدورات التدريبية / الشهادات',
    'fieldvisit': 'زيارة ميدانية',
    'visit': 'زيارة',
    'personal/fieldvisitcreation': 'إعداد التقرير الشخصي / تقرير الزيارة الميدانية',
    'citizenaffairdocuments': 'الوثائق الخاصة بقسم شؤون المواطنين',
    'personal/locationname': 'إسم الشخص / الموقع',
    'new': 'جديد',
    'new/reopened': 'الجديدة / المعاد فتحها',
    'closed/rejected': 'أغلق / مرفوض',
    'closedrejectedcard': 'تمت / رفضت',
    'needmoreinfo': 'بحاجة للمزيد من المعلومات',
    'myownrequest': 'طلباتي الخاصة',
    'citizenaffair': 'شؤون المواطنين',
    'listpage': 'القائمة',
    'citizenaffairlist': 'قائمة شؤون المواطنين',
    'createrequest': 'انشاء طلب',
    'createrequests': 'إنشاء طلبات',
    'plusCreateRequests': '+ إنشاء طلبات',
    'personalreport': 'التقرير الشخصي',
    'incomingcreation': 'إنشاء كتاب وارد',
    'didoriginalletterphysicallysend': 'هل تم إرسال الكتاب الأصلي (نسخة ورقية)؟',
    'receivingdate': 'تاريخ الاستلام',
    'receivedfromgovermententity': 'استلم من - جهة حكومية',
    'receivedfromname': 'استلم من - اسم',
    'enteroutgoingletter': 'أدخل كتاب صادر',
    'enterincomingletter': 'أدخل كتاب وارد',
    'notes': 'ملاحظات',
    'enternotes': 'ادخل الملاحظات',
    'enterkeyword': 'أدخل كلمات البحث',
    'enterref': 'أدخل الرقم المرجعي',
    'enterletter': 'أدخل أو اختر رقم الكتاب',
    'entermemo': 'أدخل أو اختر رقم المذكرة',
    'entercomments': 'أدخل تعليق',
    'selectuser': 'اختر المستخدم',
    'selectfile': 'Select file',
    'complaintssuggestions': 'الشكاوي / الاقتراحات',

    'complaintssuggestionscreation': 'إنشاء الشكاوى / اقتراحات',
    'complaintssuggestionsview': 'عرض الشكاوي / الاقتراحات',
    'complaint': 'شكوى',
    'hrcomplaint': 'شكاوى',
    'complaintassignedby': 'أسند بواسطة',
    'complaintclosedby': 'أغلق',
    'suggestions': 'اقتراحات',
    'hrsuggestions': 'اقتراحات',
    'hrdetails': 'تفاصيل',
    'hrsubmittedby': 'مقدم من',
    'hrsource': 'مصدر',
    'by': 'بواسطة',
    'type': 'النوع',
    'subject': 'الموضوع',
    'createdby': 'أنشئ من قبل',
    'myself': 'أنا',
    'hrmyself': 'أنا بنفسي',
    'anonymous': 'عدم تحديد الاسم',
    'mailid': 'البريد الالكتروني',
    'Pleaseentervalidemail': 'الرجاء إدخال معرف بريد إلكتروني صالح',
    'actiontaken': 'تم الإجراء',
    'assign': 'إسناد',
    'assignto': 'أسند إلى',
    'assigntome': 'اسناد لي',
    'assignedto': 'إسناد ل',
    'requestdate': 'تاريخ الطلب',
    'linktoletter': 'ارتباط بكتاب',
    'taskcreate': 'إنشاء مهمة',
    'attendedby': 'بحضور',
    'legalmanagement': 'الخدمات القانونية',
    'legalmanagementdashboard': 'الخدمات القانونية',
    'legaldocuments': 'الوثائق الخاصة بقسم الخدمات القانونية',
    'legalrequest': 'طلب دعم قانوني',
    'requestdetails': 'تفاصيل الطلب',
    'reopen': 'إعادة فتح',
    'requestforcampaign': 'طلب حملة',
    'requestforcampaignview': 'عرض طلب الحملة',
    'initiativeactivityprojectdetail': 'تفاصيل المبادرة / النشاط / المشروع',
    'campaignstartdate': 'تاريخ بدء الحملة',
    'campaignperiod': 'فترة الحملة',
    'diwansrole': 'دور الديوان',
    'diwansidentityrequest': 'طلب استخدام هوية الديوان',
    'otherentities': 'الجهات الأخرى',
    'targetaudience': 'الجمهور المستهدف',
    'languages': 'اللغات',
    'mediachannel': 'القنوات الإعلامية',
    'generalinformation': 'معلومات عامة',
    'mainobjective': 'الهدف الرئيسي',
    'mainidea': 'الفكرة الرئيسية',
    'requestforphotographer': 'طلب مصور',
    'viewforphotographer': 'عرض طلب المصور',
    'eventname': 'اسم الحدث/ الفعالية',
    'entereventname': 'أدخل اسم الحدث/ الفعالية',
    'enterlocation': 'أدخل الموقع',
    'enterphotodescription': 'أدخل وصف الصورة',
    'eventdate': 'تاريخ الفعالية',
    'selecteventdate': 'اختر تاريخ الحدث / الفعالية',
    'selectdate': 'حدد التاريخ',
    'trainingrequest': 'طلب دورة تدريبية',
    'trainingrequestview': 'طلب التدريب',
    'trainingfor': 'الدورة التدريبية من أجل',
    'otheremployee': 'موظف آخر',
    'traineename': 'اسم المتدرب',
    'traineeorworkshopname': 'اسم الدورة التدريبية / ورشة العمل',
    'workshop': 'ورشة عمل',
    'training': 'تدريب',
    'others': 'أخرى',
    'enddate': 'تاريخ الانتهاء',
    "internaladdressbook": 'جهات الاتصال الداخلية',
    "externaladdressbook": 'جهات الاتصال الخارجية',
    "addcontact": 'إضافة جهة اتصال',
    "internalcreation": '',
    'empPosition': 'المسمى الوظيفي',
    'addEmp': 'إضافة موظف',
    'designation': 'المسمى الوظيفي',
    "internalcontactcreation": 'إنشاء جهة اتصال داخلية',
    "internalcontactview": 'عرض جهة الاتصال الداخلية',
    "internalcontactedit": 'تحرير جهة الاتصال الداخلية',
    "externalcontactcreation": 'إنشاء جهة اتصال خارجية',
    "externalcontactview": 'عرض جهة الاتصال الخارجية',
    "externalcontactedit": 'تحرير جهة الاتصال الخارجية',
    "internalcontactupdatedsuccessfully": 'تم تحديث جهة الاتصال الداخلية بنجاح',
    "externalcontactupdatedsuccessfully": 'تم تحديث جهة الاتصال الخارجية بنجاح',
    "internalcontactsubmitsuccessfully": 'تم إنشاء جهة الاتصال الداخلية بنجاح',
    "externalcontactsubmitsuccessfully": 'تم إنشاء جهة الاتصال الخارجية بنجاح',
    "doyouwanttodeletecontact": 'هل تريد حقًا حذف جهة الاتصال هذه؟',
    "entitycontact": 'اسم الجهة ',
    "entityname": 'اسم الجهة',
    "contactname": 'اسم جهة الاتصال',
    "contacts": 'جهات الاتصال',
    "receivedfrom": 'مستلم من',
    "senderentity": 'الجهة المرسلة',
    "govtentity": 'جهة حكومية',
    "nongovtentity": 'جهة غير حكومية',
    'add': 'إضافة',
    'import': 'استيراد',
    'value': 'القيمة',
    'creation': 'إنشاء',
    'view': 'عرض',
    'memoView': 'عرض المذكرات',
    'babyname': 'اسم الطفل',
    'enterbabyname': 'أدخل اسم الطفل',
    'gender': 'الجنس',
    'male': 'ذكر',
    'female': 'أنثى',
    'birthday': 'تاريخ الميلاد',
    'hospitalname': 'اسم المستشفى',
    'enterhospitalname': 'أدخل اسم المستشفى',
    'countryofbirth': 'بلد الميلاد',
    'selectcountryofbirth': 'اختر بلد الميلاد',
    'country': 'بلد',
    'taskcountry': 'البلد',
    'cityofbirth': 'مدينة الولادة',
    'selectcityofbirth': 'اختر مدينة الميلاد',
    'countryofresidence': 'بلد الإقامة',
    'cityofresidence': 'مدينة الإقامة',
    'birthcertificate': 'شهادة الميلاد',
    'passportexpirydate': 'تاريخ انتهاء صلاحية جواز السفر',
    'visano': 'رقم التأشيرة',
    'visaissuedate': 'تاريخ إصدار التأشيرة',
    'visaexpirirydate': 'تاريخ انتهاء التأشيرة',
    'emiratesidno': 'رقم الهوية الإماراتية',
    'emiratesidexpirydate': 'تاريخ انتهاء صلاحية الهوية الإماراتية',
    'emiratesidissuedate': 'تاريخ اصدار الهوية الإماراتية',
    'insuranceno': 'رقم بوليصة التأمين الصحي',
    'insuranceissuedate': 'تاريخ إصدار التأمين الصحي',
    'insuranceexpirydate': 'تاريخ انتهاء التأمين الصحي',
    'labourcontractno': ' رقم عقد العمل',
    'labourcontractissuedate': 'تاريخ إصدار عقد العمل',
    'labourcontractexpirydate': 'تاريخ انتهاء عقد العمل',
    'updateprofile': 'تحديث الملف الشخصي',
    'update': 'تحديث',
    'viewprofile': 'عرض الشخصي',
    'giftreferencenumber': 'الرقم المرجعي للهدية',
    'giftphotos': 'صور(ة) الهدايا',
    'gifttypes': 'أنواع الهدايا',
    'gifttype': 'نوع الهدية',
    'giftrefno': 'الرقم المرجعي للهدية',
    'giftreceived': 'الهدايا المستلمة',
    'giftpushed': 'الهدايا المشتراة',
    'receivedfrompurchasedby': 'وردت من / تم شراؤها بواسطة',
    'receivedfromorganizer': 'استلمت من - الاسم',
    'dateofreceiving': 'تاريخ الاستلام',
    'purchasedby': 'تم الشراء بواسطة',
    'purchasedtoname': 'تم الشراء إلى - الاسم',
    'purchasedtoorganizer': 'تم الشراء إلى الجهة',
    'sendfordelivery': 'إرسال للتسليم',
    'confirmdelivery': 'تأكيد التوصيل',
    'handedoverto': 'سلمت ل',
    'handedoverdate': 'سلمت بتاريخ',
    'organizerdepartment': 'قسم منظم الاجتماع',
    'organizername': 'اسم منظم الاجتماع',
    'startdatetime': 'تاريخ / وقت البدء',
    'enddatetime': 'تاريخ  / وقت الانتهاء',
    'invitees': 'المدعوون',
    'internal': 'موظفو الديوان',
    'external': 'من خارج الديوان',
    'internalandexternal': 'موظفو الديوان ومدعوون من خارج الديوان​',
    'organization': 'الجهة',
    'contactperson': 'إسم جهة الاتصال',
    'viewmom': 'عرض محضر الاجتماع',
    'createmom': 'انشاء محضر اجتماع',
    'cancelmeeting': 'إلغاء اجتماع',
    'meeting': 'اجتماع',
    'sendtoinvitees': 'أرسل إلى المدعوين',
    'reshedule': 'إعادة جدولة',
    'pointsdiscussed': 'النقاط التي تمت مناقشتها',
    'pendingpoints': 'النقاط العالقة',
    'suggestionrecommendation': 'اقتراحات وتوصيات',
    'downloadmom': 'تحميل محضرالاجتماع',
    'mediarequests': 'طلبات قسم الإعلام',
    'mediarequestfordesign': 'طلب تصميم',
    'media': 'الإعلام',
    'requestforphoto': 'طلب صورة',
    'mediadocuments': 'وثائق قسم الإعلام',
    'requestfordesign': 'طلب تصميم',
    'requestforpressrelease': 'طلب بيان صحفي',
    'requestforpressreleaseview': 'عرض طلبات البيانات الصحفية',
    'requestforpressreleaseedit': 'إنشاء طلبات البيانات الصحفية',
    'requesttousediwanidentity': 'طلب استخدام هوية الديوان',
    'confirmation': 'التأكيد',
    'confirmationleavereqpastdate': 'أنت تطلب إجازة في تاريخ سابق. هل أنت متأكد أنك تريد المتابعة (نعم / لا)؟',
    'strategicgoalsplanvisionofrrc': 'كيف يمكن لهذا النشاط أن يتناسب مع الأهداف الإستراتيجية وخطة ورؤية الديوان؟',
    'filelist': 'قائمة الملفات',
    'choosefile': 'اختيار الملفات',
    'nofilechosen': 'لم تقم باختيار ملف',
    'photodescription': 'وصف الصورة',
    'addphotoforreference': 'إضافة صورة للمرجعية',
    'otherparties': 'الجهات الأخرى',
    'targetgroups': 'الفئات المستهدفة',
    'dateofdeliverable': 'تاريخ التسليم',
    'typeofdesignrequired': 'نوع التصميم المطلوب',
    'english': 'الإنجليزية',
    'arabic': 'عربي',
    'generalinformationaboutproject': 'معلومات عامة عن المشروع',
    'mainobjectiveofproject': 'الهدف الرئيسي للمشروع',
    'objectivesvisionplanofdiwan': 'كيف يتناسب هذا النشاط مع الأهداف والرؤية والخطط الإستراتيجية للديوان',
    'requestforphotoview': 'عرض طلبات الصور',
    'requestfordiwanidentity': 'طلب استخدام هوية الديوان',
    'purposeofuse': 'الغرض من الاستخدام',
    'partners': 'شركاء',
    'mediapressrelease': 'بيان صحفي',

    'request': 'طلب',
    'protocol': 'المراسم',
    'protocoldesign': 'لوحة معلومات إدارة المراسم',
    'officialtaskdescription': 'وصف المهمة الرسمية',
    'compDesc': 'تفاصيل طلب التعويض المالي',
    'compdesc': 'تفاصيل طلب التعويض المالي',
    'doyouneedhospitalitycompensation': 'طلب الاستضافة / التعويض؟',
    'officialtaskrequestview': 'عرض طلب مهمة رسمية',
    'plsSelEndDate': 'الرجاء تحديد تاريخ النهاية',
    'plsSelValDateRange': 'الرجاء تحديد الفترة بشكل صحيح',
    'offcTaskReqSubSuc': 'تم بنجاح إرسال طلب المهمة الرسمية',
    'compReqSubSuc': 'تم تقديم طلب التعويض بنجاح',
    'comReqReSubSuc': 'تمت إعادة إرسال طلب التعويض المالي',
    'compReqAppAssSuc': 'تمت الموافقة على طلب التعويض واسناده بنجاح',
    'compReqAssSuc': 'تم إسناد طلب التعويض المالي بنجاح',
    'compReqEsclSuc': 'تم رفع طلب التعويض المالي للموافقة',
    'compReqAppSuc': 'تمت الموافقة على طلب التعويض بنجاح',
    'compReqRejSuc': 'تمت رفض طلب التعويض بنجاح',
    'compReqReturnedSuc': 'تمت إعادة طلب التعويض لمزيد من المعلومات',
    'compReqClosedSuc': 'تم إغلاق طلب التعويض بنجاح',
    'offcReqCmpltSuc': 'تم إكمال المهمة الرسمية بنجاح',
    'anonymousdontshowmyname': 'مجهول(لا تظهر اسمي)',
    'employeedepartment': 'القسم',
    'employeename': 'اسم الموظف',
    'employeecode': 'الرقم الوظيفي',
    'systemadmin': 'مسؤول النظام',
    'grade': 'الدرجة الوظيفية',
    'officialtasktype': 'نوع المهمة الرسمية',
    'numberofdays': 'عدد الأيام',
    'markascompleted': 'تغيير كمنتهي',
    'closeraisecompensation': 'إغلاق وإرسال طلب التعويض المالي',
    'staffhospitality': 'الاستضافة',
    'officialmailid': 'البريد الالكتروني الرسمي',
    'personalmailid': 'البريد الإلكتروني الشخصي',
    'trainingname': 'اسم التدريب',
    'officialtaskrequestassignment': 'إسناد مهمة رسمية',
    'officialtaskapproval': 'موافقة المهام الرسمية',
    'generateadministartivedecision': 'قرار إداري عام',
    'balanceleave': 'رصيد الإجازات',
    'reason': 'السبب',
    'requestordepartment': 'القسم المتقدم بالطلب',
    'requestorname': 'اسم مقدم الطلب',
    'maintenancedocuments': 'وثائق قسم الصيانة',
    'enterlabel': 'إدخال كلمة بحثية',
    'laststatusupdateat': 'آخر تحديث للحالة في',
    'itsupport': 'الدعم',
    'printnotworkingemailissueetc': 'الطباعة لا تعمل ، مشكلة في البريد الإلكتروني ، إلخ',
    'itservice': 'الخدمات',
    'supportanypresentationdeskshifting': 'تحضير عرض تقديمي ، نقل مكتب',
    'itcomponents': 'مكونات تكنولوجيا المعلومات',
    'informationtechnology': 'تكنولوجيا المعلومات',
    'selectrequestername': 'حدد اسم مقدم الطلب',
    'selectrequesterdepartment': 'اختر قسم مقدم',
    'support': 'الدعم',
    'services': 'خدمات',
    'components': 'مكونات',
    'itdocuments': 'وثائق تكنولوجيا المعلومات',
    'uploadeddate': 'تاريخ التحميل',
    'addcomment': 'أضف تعليق',
    'cancel': 'إلغاء',
    'underprocess': 'قيد الإجراء',
    'memodraftsuccess': 'تم حفظ مسودة المذكرة بنجاح',
    'memosentsuccess': 'تم إرسال المذكرة بنجاح',
    'memoreturnsuccess': 'تمت إعادة الإرسال بنجاح',
    'memoapprovesuccess': 'تم اعتماد المذكرة بنجاح',
    'memorejectsuccess': 'تم رفض المذكرة بنجاح',
    'memoclosesuccess': 'تم إغلاق المذكرة بنجاح',
    'memoclonesuccess': 'تم النسخ من قبل',
    'memodeletesuccess': 'تم حذف المذكرة بنجاح',
    'memoSharedsuccess': 'تمت مشاركة المذكرة بنجاح',
    'memo': 'مذكرة',
    'taskihaveassigned': 'المهام المسندة من قبلي',
    'leavetype': 'نوع الإجازة',
    'mytask': 'مهامي',
    'participants': 'المشاركون في المهام',
    'uncompletedtaskperpriorities': 'المهام غير المكتملة حسب الأولويات',
    'taskperstatus': 'المهام حسب الحالة',
    'taskinprogress': 'المهام قيد الإجراء',
    'taskcompleted': 'المهام المكتملة',
    'taskclosed': 'المهام المغلقة',
    'assignee': 'المكلف',
    'lastupdate': 'آخر تحديث',
    'dutytask': 'المهام',
    'tasklist': 'قائمة المهام',
    'communicationboardtitle': 'لوح النقاش / سجلات المهمة',
    'eventrequestor': 'طالب الحدث/ الفعالية',
    'eventtype': 'نوع الحدث/ الفعالية',
    'approved': 'وافق',
    'completed': 'منجز',
    'cancelled': 'ملغى',
    'eventdetails': 'تفاصيل الحدث/ الفعالية',
    'alldayevents': 'الحدث/ الفعالية في كامل اليوم',
    'addmoreevent': 'إضافة المزيد من الأحداث/ الفعاليات',
    'createevent': 'انشاء حدث/ فعالية',
    'proposedby': 'اقترح بواسطة',
    'addmore': 'أضف المزيد',
    'addmorereminder': 'إضافة تذكيراخر',
    'addmoreinternalinvitees': 'إضافة المزيد من المدعوين الداخليين',
    'addmoreexternalinvitees': 'إضافة مدعوين خارجيين',
    'calendarview': 'عرض التقويم',
    'viewevent': 'عرض الحدث/ الفعالية',
    'reschedule': 'إعادة جدولة',
    'createmeeting': 'إنشاء اجتماع',
    'editmeeting': 'تحرير الاجتماع',
    'viewmeeting': 'عرض الاجتماع',
    'meetingtype': 'نوع الاجتماع',
    'creategift': 'إنشاء هدايا',
    'mypendingactions': 'أعمالي المعلقة',
    'mycalendar': 'جدول اجتماعاتي',
    'showlistview': 'اعرض القائمة',
    'humanresource': 'الموارد البشرية',
    'createofficialtask': 'إنشاء طلب مهمة رسمية',
    'createcompensationrequest': 'إنشاء طلب تعويض',
    'viewcompensationrequest': 'عرض طلب التعويض',
    'myevents': 'أحداثي/ فعالياتي',
    'calendarmanagement': 'إدارة التقويم',
    'giftmanagement': 'إدارة الهدايا',
    'apologiesalert': 'تقديم خطاب اعتذار',
    'doyouwanttosentanaplologiesletter': 'هل تريد إرسال خطاب اعتذار؟',
    'homepage': 'الصفحة الرئيسية',
    'doaname': 'تفويض - الاسم',
    'doadepartment': 'تفويض - القسم',


    'mailremainderfrequency': 'تكرار تذكيرات البريد الالكتروني',
    'remaindershouldbelessthanmeetingstartdate': 'يجب أن يكون تاريخ ووقت التذكير قبل تاريخ بدء الاجتماع ووقته',
    'mailnotification': 'إشعارات البريد الالكتروني',
    'approvers': 'قائمة المخولين بالاعتماد',
    'dept': 'قسم',
    'masterdata': 'البيانات الرئيسية',
    'usermanagement': 'إدارة المستخدمين',
    'userlogonname': 'اسم المستخدم',
    'section': 'قسم',
    'unit': 'وحدة',
    'headofdepartment': 'رئيس الادارة',
    'headofsection': 'رئيس القسم',
    'headofunit': 'رئيس الوحدة',
    'canraiseofficialrequest': 'يتمكن من انشاء مهام رسمية',
    'canmanagenewsphotos': 'يمكن إدارة الأخبار / الصور',
    'holidays': 'العطل الرسمية',
    'importholidayslist': 'تحميل قائمة العطل الرسمية',
    'clicktoviewholidays': 'انقر لعرض العطلات الرسمية',
    'masteradmin': 'ادارة المتغيرات',
    'settings': 'الإعدادات',
    'rejectedby': 'مرفوض من طرف',
    'returnedforinfoby': 'أعيد للحصول على معلومات من قبل',
    'markascompletedby': 'أكتمل بواسطة',
    'closeandraisecompensationby': 'رفع طلب التعويض بواسطة',
    'cancelledby': 'تم الإلغاء بواسطة',
    'assignedby': 'أسند من قبل',
    'resubmittedby': 'إعادة تقديم بواسطة',
    'reopenedby': 'إعادة فتح بواسطة',
    'rescheduledby': 'إعادة جدولة بواسطة',
    'passport': 'جواز السفر',
    'visa': 'تأشيرة الفيزا',
    'jobtitle': 'المسمى الوظيفي',
    'mr': 'السيد',
    'mrs': 'السيدة',
    'eventsview': 'Events View',
    'createevents': 'Create Events',

    'pleaseenteravalidenddate': 'الرجاء ادخال تاريخ صحيح',
    'pleaseselectvalidstarttime': 'يرجى إختيار وقت البدء بشكل صحيح',
    'pleaseselectstartdateandtime': 'Please select Start Date and Time',
    'error': 'خطأ',
    'errormsgemployeename': 'الرجاء إدخال اسم الموظف بشكل صحيح',
    'errormsggender': 'يرجى اختيار الجنس',
    'errormsgemployeecode': 'الرجاء إدخال الرقم الوظيفي',
    'errormsgvalidmailid': 'الرجاء إدخال بريد إلكتروني صحيح!',
    'errormsgofficialmailid': 'الرجاء إدخال البريد الالكتروني الرسمي',
    'errormsgpersonalmailid': 'الرجاء إدخال البريد الإلكتروني الشخصي',
    'errormsgcountryofresidence': 'الرجاء إدخال بلد الإقامة  بشكل صحيح',
    'errormsgmobileno': 'الرجاء إدخال رقم الجوال  بشكل صحيح',
    'errormsgemployeephoneno': 'يرجى إدخال رقم هاتف الموظف بشكل صحيح',
    'errormsgnationality': 'يرجى تحديد الجنسية  بشكل صحيح',
    'errormsgreligion': 'يرجى تحديد الديانة بشكل صحيح',
    'errormsgprenationality': 'يرجى تحديد الجنسية السابقة بشكل صحيح',
    'errormsgjoindate': 'يرجى تحديد تاريخ الانضمام صالح',
    'errormsgtitle': 'يرجى تحديد العنوان  بشكل صحيح',
    'errormsggrade': 'يرجى اختيار الدرجة الوظيفية',
    'errormsgemploymentstatus': 'يرجى اختيار الحالة الوظيفية بشكل صحيح',
    'errormsgresigned': 'يرجى اختيار االشخص المعاد تكليفه',
    'errormsgfieldstudy': 'يرجى إدخال مجال الدراسة',
    'errormsgvaliddegree': 'يرجى اختيار الدرجة الوظيفية بشكل صحيح',
    'errormsgcollegeschool': 'يرجى إدخال المدرسة / الكلية ',
    'errormsgtimeperiodfrom': 'يرجى تحديد الفترة زمنية - إلى',
    'errormsgtimeperiodto': 'يرجى تحديد الفترة زمنية - من',
    'errormsgvalidtitle': 'يرجى اختيار المسمى الوظيفي بشكل صحيح',
    'errormsgvalidcompany': 'يرجى إدخال اسم الشركة بشكل صحيح ',
    'errormsgvalidcity': 'الرجاء إدخال المدينة بشكل صحيح',
    'errormsgtrainingname': 'يرجى اختيار اسم البرنامج التدريبي بشكل صحيح',
    'errormsgvalidstartdate': 'يرجى تحديد تاريخ البدء بشكل صحيح',
    'errormsgvaliddaterange': 'الرجاء تحديد الفترة بشكل صحيح',
    'errormsgvalidenddate': 'يرجى تحديد تاريخ البداية / النهاية بشكل صحيح',
    'errormsgpasportno': 'الرجاء إدخال رقم جواز سفر بشكل صحيح',
    'errormsgvisano': 'الرجاء إدخال رقم التأشيرة بشكل صحيح',
    'errormsgpasportplace': 'الرجاء إدخال مكان إصدار جواز السفر',
    'errormsgemiratesno': 'الرجاء إدخال رقم هوية الإماراتية سارية المفعول',
    'errormsgcontractno': 'الرجاء إدخال رقم عقد عمل صالح',
    'errormsgvalidattachements': 'يرجى تحميل المرفقات بشكل صحيح',
    'errormsgvaliddigitalsignature': 'يرجى تحميل التوقيع الرقمي بشكل صحيح',
    'errormsgbirthdate': 'يرجى تحديد تاريخ الميلاد بشكل صحيح',
    'errormsgvalidbirthdate': 'يجب أن يكون العمر أكثر من 18 عاماً. يرجى إدخال تاريخ الميلاد لشكل صحيح',
    'errormsgvaliddepartment': 'يرجى إختيار الإدارة أو المكتب',
    'errormsgemployeeposition': 'يرجى إدخال المسمى الوظيفي بشكل صحيح',
    'errormsgresigndate': 'يرجى تحديد تاريخ الاستقالة بشكل صحيح',
    'errormsgvalidnotifipreferences': 'يرجى تحديد تفضيلات الإشعارات بشكل صحيح',
    'errormsgvalidenddateshouldgtstartdate': 'يجب أن يكون تاريخ الإنتهاء بعد تاريخ البدء',
    'errormsgvalidpassportissuedate': 'يرجى تحديد تاريخ إصدار جواز سفر بشكل صحيح',
    'errormsgvalidpassportexpirydate': 'يرجى تحديد تاريخ انتهاء صلاحية جواز السفر',
    'errormsgvalidvisaissuedate': 'يرجى إدخال تاريخ إصدار تأشيرة ساري المفعول',
    'errormsgvalidvisaexpirydate': 'يرجى إدخال تاريخ انتهاء صلاحية التأشيرة',
    'errormsgemiratesissuedate': 'يرجى إدخال تاريخ إصدار الهوية الإماراتية سارية المفعول',
    'errormsgemiratesexpirydate': 'يرجى إدخال تاريخ انتهاء صلاحية الهوية الأماراتية',
    'errormsglabourcontractorissuedate': 'الرجاء إدخال تاريخ إصدار عقد العمل',
    'errormsglabourcontractorexpirydate': 'الرجاء إدخال تاريخ انتهاء عقد العمل',
    'errormsgvaliddocumenttype': 'يرجى اختيار نوع المستند بشكل صحيح',
    'documenttype': 'نوع المستند',
    'uploadpersonaldocument': 'تحميل المستندات الشخصية',
    'signature': 'التوقيع',
    'vacation': 'عطلة',
    'sickleave': 'اجازة مرضية',
    'Howdoesthisactivityfitwiththestrategicobjectivesvisionandplansofthediwan': 'كيف يتناسب هذا النشاط مع الأهداف والرؤية والخطط الإستراتيجية للديوان',
    'deliveryconfirmedby': 'تأكيد التوصيل بواسطة',
    'sentfordeliveryby': 'أرسلت للتسليم بواسطة',
    'meetingid': 'معرف الاجتماع',
    'attendees': 'الحاضرين',
    'createtask': 'خلق مهمة',
    'protocolcalendar': 'التقويم المراسم',
    'bulk': 'إنشاء متعدد',
    'month': 'شهر',
    'day': 'يوم',
    'am': 'صباحا',
    'pm': 'مساء',
    'reply': 'الرد',
    'selecttime': 'اختر الوقت',
    'selectauser': 'اختر مستخدم',

    'photosubmittedby': 'مقدم بواسطة',
    'photoapprovedby': 'تمت الموافقة عليه من قبل',
    'photorejectedby': 'مرفوض من طرف',
    'photoescalatedby': 'تم الرفع للموافقة بواسطة',
    'photoreturnforinfoby': 'أعيد للحصول على معلومات بواسطة',
    'photoassignedby': 'أسند من قبل',
    'photoresubmittedby': 'أعيد التقديم بواسطة',
    'photosourcename': 'اسم المصدر',
    'photosubmitsuccessmsg': 'تم تقديم طلب الصورة بنجاح',
    'photoresubmitsuccessmsg': 'تم إعادة إرسال طلب الصورة بنجاح',
    'photoapprovesuccessmsg': 'تم الموافقة على طلب الصورة بنجاح',
    'photoescalatesuccessmsg': 'طلب صور رفع للموافقة بنجاح',
    'photoreturnforinfosuccessmsg': 'تم إرجاع طلب الصورة للحصول على معلومات بنجاح',
    'photoassignsuccessmsg': 'أسند طلب الصور بنجاح',
    'photoclosesuccessmsg': 'تم اغلاق طلب الصور بنجاح',
    'photorejectsuccessmsg': 'تم رفض طلب الصورة بنجاح',

    'designsubmitmsg': 'تم تقديم طلب التصميم بنجاح',
    'designapprovedmsg': 'تمت الموافقة على طلب التصميم بنجاح',
    'designescalatemsg': 'طلب التصميم تم رفعه للموافقة بنجاح',
    'designreturnedmsg': 'طلب التصميم أعيد للحصول على معلومات بنجاح',
    'designassignedmsg': 'طلب التصميم تم اسناده بنجاح',
    'designclosedmsg': 'تم إغلاق طلب التصميم بنجاح',
    'designrejectmsg': 'تم رفض طلب التصميم بنجاح',

    'campaignsubmitmsg': 'تم تقديم طلب الحملة بنجاح',
    'campaignapprovedmsg': 'تم اعتماد طلب الحملة بنجاح',
    'campaignescalatemsg': 'طلب الحملة رفع للموافقة بنجاح',
    'campaignreturnedmsg': 'تم إرجاع طلب الحملة للحصول على معلومات بنجاح',
    'campaignassignedmsg': 'تم تخصيص طلب الحملة بنجاح',
    'campaignclosedmsg': 'تم إغلاق طلب الحملة بنجاح',
    'campaignrejectdmsg': 'تم رفض طلب الحملة بنجاح',
    'campaignresubmitdmsg': 'تم إعادة تقديم طلب الحملة بنجاح',

    'photographersubmitmsg': 'تم تقديم طلب المصور بنجاح',
    'photographerresubmitmsg': 'تم إعادة تقديم طلب المصور بنجاح',
    'photographerapprovedmsg': 'تمت الموافقة على طلب المصور بنجاح',
    'photographerescalatemsg': 'طلب مصور رفع للموافقة بنجاح',
    'photographerreturnedmsg': 'طلب مصور تم إرجاعه للحصول على معلومات بنجاح',
    'photographerassignedmsg': 'طلب مصور تم اسناده بنجاح',
    'photographerclosedmsg': 'تم إغلاق طلب المصور بنجاح',
    'photographerrejectedmsg': 'تم رفض طلب المصور بنجاح',

    'diwanidentitysubmitmsg': 'تم تقديم طلب استخدام هوية الديوان بنجاح',
    'diwanidentityapprovedmsg': 'تمت الموافقة على طلب استخدام هوية الديوان بنجاح',
    'diwanidentityescalatemsg': 'تم الرفع للموافقة على طلب استخدام هوية الديوان بنجاح',
    'diwanidentityreturnedmsg': 'تمت اعادة طلب استخدام هوية الديوان للحصول على معلومات بنجاح',
    'diwanidentityassignedmsg': 'تم اسناد طلب استخدام هوية الديوان بنجاح',
    'diwanidentityclosedmsg': 'تم اغلاق طلب استخدام هوية الديوان بنجاح',
    'diwanidentityrejectmsg': 'تم رفض طلب استخدام هوية الديوان',

    'pressreleasesubmitmsg': 'تم تقديم طلب تحرير الخبر الصحفي بنجاح',
    'pressreleaseapprovedmsg': 'تم اعتماد طلب تحرير الخبر الصحفي بنجاح',
    'pressreleaseescalatemsg': 'تم رفع طلب تحرير الخبر الصحفي للموافقة بنجاح',
    'pressreleasereturnedmsg': 'تمت اعادة طلب تحرير الخبر الصحفي للحصول على معلومات بنجاح',
    'pressreleaseassignedmsg': 'تم اسناد طلب تحرير الخبر الصحفي بنجاح',
    'pressreleaseclosedmsg': 'تم إغلاق طلب تحرير الخبر الصحفي بنجاح',
    'pressreleaserejectdmsg': 'تم رفض طلب البيان الصحفي بنجاح',
    'pressreleaseresubmitdmsg': 'تمت إعادة تقديم طلب البيان الصحفي بنجاح',

    'leavecloseemsg': 'طلب الاجازة أغلق بنجاح',
    'leaveassignmsg': 'تم إسناد طلب الاجازة بنجاح',
    'leaveupdatemsg': 'تم تحديث طلب الإجازة بنجاح',
    'leavereturnedmsg': 'أرجع طلب الإجازة لمزيد من المعلومات',
    'leaveescalatemsg': 'تم رفع طلب الإجازة للموافقة',
    'leaverejectmsg': 'تم رفض طلب الاجازة ',
    'leaveapprovedmsg': 'تمت الموافقة على طلب الاجازة',
    'leavecreatedmsg': 'تم إنشاء طلب الإجازة بنجاح',
    'leaveapprovedandassignsuccessmsg': 'طلب الإجازة تمت الموافقة عليه واسناده بنجاح',
    'leavereqassignmsg': 'تم إسناد طلب الإجازة بنجاح',

    'salarycertificatecreatedmsg': 'تم إنشاء طلب شهادة الراتب بنجاح',
    'salarycertificateassignedmsg': 'تم إسناد طلب شهادة الراتب بنجاح',
    'salarycertificateclosedmsg': 'تم إغلاق طلب شهادة الراتب بنجاح',

    'experiencecertificatecreatedmsg': 'تم إنشاء طلب شهادة الخبرة بنجاح',
    'experiencecertificateassignedmsg': 'تم إسناد طلب شهادة الخبرة بنجاح',
    'experiencecertificateclosedmsg': 'تم إغلاق طلب شهادة الخبرة بنجاح',

    'newbabyadditionreqcreatedmsg': 'تم إنشاء طلب إضافة طفل جديد بنجاح',
    'newbabyadditionreqassignedmsg': 'تم إسناد طلب إضافة الطفل الجديد بنجاح',
    'newbabyadditionreqclosedmsg': 'تم إكمال طلب إضافة الطفل الجديد بنجاح',

    'trainingreqcreatemsg': 'تم إنشاء طلب الدورة التدريبية بنجاح',
    'trainingreqapprovedmsg': 'تم اعتماد طلب التدريب بنجاح',
    'trainingreqescalatemsg': 'تم رفع طلب التدريب للإعتماد بنجاح',
    'trainingreqreturnedmsg': 'أعيد طلب التدريب لمزيد من المعلومات',
    'trainingrequpdatemsg': 'تم تحديث طلب التدريب بنجاح',
    'trainingreqrejectmsg': 'تم رفض طلب التدريب بنجاح',
    'traingreqassignmsg': 'عرض السيرة الذاتية',

    'circularcreate': 'إنشاء تعميم',
    'circularview': 'عرض التعميم',
    'circularedit': 'تعديل التعميم الإداري',
    'circulardatefrom': 'تاريخ الانشاء - من',
    'circulardateto': 'تاريخ الانشاء - إلى',
    'internalcirculars': 'التعميمات ادارية',
    'internalletters': 'التعميمات ادارية',
    'circulardrafted': 'مسودة التعميمات الإدارية',
    'circularsubmitted': 'تم إرسال التعميم بنجاح',
    'circularupdate': 'تم تحديث التعميم بنجاح',
    'circularreturninfo': 'إعادة تقديم التعميم بنجاح',
    'circularapproved': 'تمت الموافقة على التعميم بنجاح',
    'circularreject': 'تم رفض التعميم بنجاح',
    'circularclonedsuccessfully': 'تم نسخ التعميم نجاح',
    'circularescalatedsuccessfully': 'تم رفع التعميم للموافقة بنجاح',
    'circulardeletedsuccessfully': 'تم رفع التعميم للموافقة بنجاح',

    'legalreqcreatemsg': 'تم تقديم طلب الاستشارة القانونية بنجاح',
    'legalreqreturnedmsg': 'تم إرجاع طلب الاستشارة القانونية للحصول على معلومات بنجاح',
    'legalrequpdatemsg': 'تم تقديم طلب الاستشارة القانونية بنجاح',
    'legalassignedmsg': 'تم إسناد طلب الاستشارة القانونية بنجاح',
    'legalclosedmsg': 'تم إغلاق طلب الاستشارة القانونية بنجاح',
    'legalreopenedmsg': 'تم إعادة فتح طلب الاستشارة القانونية بنجاح',

    'maintenance': 'الصيانة',
    'maintenancerequestview': 'عرض طلب الصيانة',
    'maintenancereqcreatemsg': 'تم تقديم طلب الصيانة بنجاح',
    'maintenancereqapprovedmsg': 'تمت الموافقة على طلب الصيانة بنجاح',
    'maintenancereqescalatemsg': 'تم رفع طلب الصيانة للاعتماد بنجاح',
    'maintenancereqreturnedmsg': 'طلب صيانة تم إرجاعه للحصول على معلومات بنجاح',
    'maintenancerequpdatemsg': 'تم إعادة تقديم طلب الصيانة بنجاح',
    'maintenancereqrejectmsg': 'تم إغلاق طلب الصيانة بنجاح',
    'maintenanceassignedmsg': 'تم اسناد طلب الصيانة بنجاح',
    'maintenanceclosedmsg': 'تم إغلاق طلب الصيانة بنجاح',
    'maintenancelreqescalatemsg': 'تمت الموافقة على طلب الصيانة واسناده بنجاح',

    'employeeprofileupdatemsg': 'تم تحديث ملف تعريف الموظف بنجاح',
    'calendarreqcreatemsg': 'تم تقديم طلب الحدث/ الفعالية بنجاح',
    'calendarreqapprovemsg': 'تم اعتماد طلب الحدث/ الفعالية بنجاح',
    'calendarreqescalatedmsg': 'طلب الحدث/ الفعالية رفع للموافقة بنجاح',
    'calendarreqreturnmsg': 'تم إرجاع طلب الحدث/ الفعالية للحصول على معلومات بنجاح',
    'calendarreqassignmsg': 'تم إسناد طلب الحدث/ الفعالية بنجاح',
    'calendarreqmarkascompletemsg': 'تم إكمال الحدث/ الفعالية بنجاح',
    'calendarreqrejectmsg': 'تم رفض طلب الحدث بنجاح',

    'meetingreqcreatemsg': 'تم التقديم بنجاح',
    'momreqcreatemsg': 'تم إنشاء الاجتماع وإرسال الدعوة بنجاح',
    'meetingreqreschedulemsg': 'تمت إعادة جدولة الاجتماع بنجاح',
    'meetingreqcancelmsg': 'تم الغاء الاجتماع بنجاح',

    'tasksubmittedsuccessfully': 'تم إنشاء المهمة بنجاح',
    'taskdeletedsuccessfully': 'تم حذف المهمة بنجاح',
    'taskclosedsuccessfully': 'تم إغلاق المهمة بنجاح',
    'taskcompletedsuccessfully': 'اكتملت المهمة بنجاح',
    'taskview': 'عرض المهمة',
    'linktomeeting': 'ارتباط بإجتماع',
    'entermeeting': 'أدخل أو اختر رقم الإجتماع',
    'typeyourmessage': 'اكتب رسالتك',
    'duedatefrom': 'تاريخ التنفيذ - من',
    'duedateto': 'تاريخ التنفيذ – إلى',
    'datefrom': 'التاريخ من',
    'linkto': 'رابط إلى',
    'rooms': 'RoomAR',
    'guest': 'GuestAR',
    'Invalidrefidoraccesstothisrefidisdenied': 'الرقم المرجعي غير صالح أو لا يمكنك الوصول إلى هذا الرقم المرجعي',
    'gm': 'صباح الخير',
    'ga': 'مساء الخير',
    'giftsentfordeliverysuccessfully': 'تم إرسال الهدية للتسليم بنجاح',
    'giftrequestsuccessmsg': 'تم تقديم طلب الهدية بنجاح',
    'giftdeliveryconfirmedsuccessfully': 'تأكيد تسليم الهدايا بنجاح',
    'description': 'التفاصيل',
    'photo': 'الصور',
    'news': 'خبریں',
    'isprivate': 'المشاركة مع الزملاء؟',
    'allsearchresult': 'كل نتائج البحث',
    'resultinall': 'نتيجة الكل',
    'allday': 'طوال اليوم',
    'documents': 'مستندات',
    'upload': 'رفع',
    'documentlistpage': 'صفحة قائمة المستندات',
    'legalservices': 'الخدمات القانونية',
    'noItemsFound': 'لم يتم العثور على العناصر',
    'photoaddedsuccessfully': 'تمت إضافة الصورة بنجاح',
    'newsaddedsuccessfully': 'تمت إضافة الخبر بنجاح',
    'banneraddedsuccessfully': 'الصورة الرئيسية أضيفت بنجاح',
    'newsupdatedsuccessfully': 'تم تحديث الخبر بنجاح',
    'photoupdatedsuccessfully': 'Photo Updated Successfully',
    'inprogress': 'قيد الإنجاز',
    'inprogresscard': 'قيد الإجراء ',
    'sourceou': 'صادر من',
    'englishvalue': 'بالانجليزية',
    'arabicvalue': 'بالعربية',
    'specialization': 'التخصص',
    'officialtaskrequest': 'طلب مهمة رسمية',
    'experience': 'الخبرة',
    'employeestatus': 'حالة الموظف',
    'designtype': 'نوع التصميم',
    'caneditcontacts': 'يمكنه إدارة جهات الاتصال؟',
    'dropdowndeletedialogmsg': 'هل أنت متأكد أنك تريد حذف هذه القيمة؟',
    'edituserdetailsdialogtitle': 'تحرير تفاصيل المستخدم',

    'dropdownreqcreatemsg': 'تمت إضافة القائمة المنسدلة بنجاح',
    'dropdownrequpdatemsg': 'تم تحديث القائمة المنسدلة بنجاح',
    'dropdownreqdeletemsg': 'تم حذف القائمة المنسدلة بنجاح',
    'userdatarequpdatemsg': 'تم تحديث بيانات المستخدم بنجاح',
    'holidayslistimportmsg': 'تم إدخال قائمة الإجازات بنجاح',
    'mailreminderreqcreatemsg': 'تم حفظ إعدادات التذكير بنجاح',
    'mailreminderrequpdatemsg': 'تم تحديث إعدادات تذكير البريد بنجاح',
    'approverrequpdatemsg': 'تم تحديث قائمة المخولين بالإعتماد بنجاح',

    'complaintsuggestionsubmitted': 'تم تقديم الاقتراح/الشكوى بنجاح',
    'complaintsuggestionclosed': 'تم إغلاق الاقتراح/ الشكوى بنجاح',
    'complaintsuggestionassigned': 'تم تقديم الاقتراح/ الشكوى بنجاح',

    'hours': 'ساعات',

    'letterclonedsuccessfully': 'تم نسخ الكتاب بنجاح',
    'letterrejectedsuccessfully': 'تم رفض الكتاب بنجاح',
    'letterdraftsaved': 'تم حفظ مسودة الكتاب',
    'letterdeletedsuccessfully': 'تم حذف الكتاب بنجاح',
    'letterredirectedsuccessfully': 'تمت اعادة توجيه الكتاب الوارد بنجاح',
    'letterescalatedsuccessfully': 'تم رفع الكتاب الوارد للاعتماد بنجاح',
    'letterapprovedsuccessfully': 'تم اعتماد الكتاب بنجاح',
    'lettersentsuccessfully': 'تم إرسال الكتاب بنجاح',
    'letterclosedsuccessfully': 'تم اكمال الكتاب بنجاح',
    'addvalue': 'إضافة قيمة',
    'editvalue': 'تحرير القيمة',
    'deletevalue': 'حذف القيمة',
    'Saved': 'حفظ بواسطة',
    'savedby': 'حفظ بواسطة',
    'createdutytaskrelated': 'إنشاء المهام ذات الصلة',
    'Closed': 'أغلقت بواسطة',
    'Cloned': 'نسخت بواسطة',
    'today': 'اليوم',
    'yesterday': 'الأمس',
    'monday': 'الإثنين',
    'tuesday': 'الثلاثاء',
    'wednesday': 'الأربعاء',
    'thursday': 'الخميس',
    'friday': 'الجمعة',
    'saturday': 'السبت',
    'sunday': 'الأحد',
    'itrequestview': 'عرض الطلبات',
    'itcreaterequest': 'انشاء طلب لقسم تكنولوجيا المعلومات',
    'itsupportreqsubmitmsg': 'تم تقديم طلب الدعم التقني بنجاح',
    'requestcreation': ' إنشاء طلب',
    'requestview': 'عرض الطلبات',
    'myclosedrequest': 'طلباتي المغلقة',
    'supportnew': 'طلب دعم جديد',
    'supportinprogress': 'طلب الدعم قيد الإجراء',
    'supportclosed': 'طلب الدعم مغلق',
    'servicesnew': 'طلب خدمة جديدة',
    'servicesinprogress': 'طلب الخدمة قيد الإجراء',
    'servicesclosed': 'طلب الخدمة مغلق',
    'componentsnew': 'طلب جديد',
    'componentsinprogress': 'طلب قيد الإجراء',
    'componentsclosed': 'الطلب مغلق',
    'itdashboard': 'لوحة المعلومات',
    'edit': 'إنشاء',
    'emailvalidationerror': 'الرجاء إدخال معرف بريد إلكتروني صالح',
    'reporter': 'AR_Reporter',
    'reporterlabel': 'المنشئ',
    'reportedby': 'أرسل بواسطة',
    'reportername': 'اسم المرسل',
    'personal/fieldvisitreport': 'عرض تقرير شخصي/تقرير زيارة ميدانية',
    'personal/fieldvisitreportcreation': 'إنشاء تقرير شخصي / تقرير زيارة ميدانية',
    'personal/fieldvisitreportview': 'عرض التقرير الشخصي / تقرير الزيارة الميدانية',
    'citizendraftsuccess': 'تم حفظ مسودة الطلب بنجاح',
    'citizensubmitsuccess': 'تم تقديم طلب شؤون المواطنين بنجاح',
    'citizenapprved': 'تم اعتماد طلب شؤون المواطنين بنجاح',
    'citizenrejected': 'تم رفض طلب شؤون المواطنين بنجاح',
    'citizenclosed': 'تم إغلاق طلب شؤون المواطنين بنجاح',
    'citizenresubmittedsuccess': 'تمت إعادة تقديم طلب شؤون المواطنين بنجاح',
    'citizenreturn': 'تم بنجاح إرجاع الطلب للحصول على معلومات إضافة',

    'insurance': 'التأمين الصحي',
    'labourcontract': 'عقد العمل',
    'dashboard': 'لوحة العرض',
    'salarycertificaterequest': 'طلب شهادة راتب',
    'experiencecertificaterequest': 'طلب شهادة خبرة',
    'newbabyadditionrequest': 'طلب إضافة طفل جديد',
    'createleaverequest': 'طلب إجازة',
    'completebtnnote': 'ملاحظة: يرجى التواصل مع منشئ المهمة ليؤكد اكتمالها قبل الضغط على زر اكتملت',
    'office/departments': 'المكتب/ الإدارة',
    'officedepartments': 'المكتب/ الإدارة',
    'managenews': 'إدارة الأخبار',
    'managebanner': 'إدارة الصورة الرئيسية',
    'banner': 'الصورة الرئيسية',
    'managegallery': 'إدارة الصور',
    'deletephotomessage': 'هل تريد حقًا حذف هذه الصورة?',
    'deletemessage': 'هل أنت متأكد أنك ترغب بحذف هذا الخبر',
    'incomingletters': 'الكتب الواردة',
    'outgoingletters': 'الكتب الصادرة',
    'My Pending Actions Incoming': 'الوارد - بحاجة للإطلاع',
    'My Pending Actions Outgoing': 'الصادر - بحاجة للإطلاع',
    'Incoming Letters': 'الكتب الواردة',
    'Outgoing Letters': 'الكتب الصادرة',
    'Draft Letters': 'مسودة الكتب',
    'Historical Letters': 'الكتب المؤرشفة',
    'create': 'إنشاء',

    'personal/fieldvisitview': 'عرض تقرير شخصي/تقرير زيارة ميدانية',
    'personal/fieldvisitedit': 'تحرير تقرير شخصي/ زيارة ميدانية',
    'trainingreqapproveassignmsg': 'تمت الموافقة على طلب التدريب واسناده بنجاح',
    'trainingreqassignmsg': 'تم إسناد طلب التدريب بنجاح',
    'trainingreqclosemsg': 'تم إغلاق طلب التدريب بنجاح',
    'hrmyprocessedrequest': 'الطلبات المنجزة بواسطتي',
    'leaverequestspopuptitle': 'طلب إجازة',
    'salarycertificaterequestpopuptitle': 'طلب شهادة راتب',
    'experiencecertificatepopuptitle': 'طلب شهادة خبرة',
    'newbabyadditionpopuptitle': 'طلب إضافة طفل جديد',
    'announcementrequestspopuptitle': 'طلب إعلان',
    'trainingrequestspopuptitle': 'طلب تدريب',
    'raisecomplaintssuggestionspopuptitle': 'طلب الشكاوي / والاقتراحات',
    'nodatatodisplay': 'لا يوجد أي بيانات للعرض',
    'humanresources': 'الموارد البشرية',
    'protocolservices': 'خدمات المراسم',
    'photographer': "مصور فوتوغرافي",
    'photogallery': "معرض الصور",

    'selectstatus': 'اختر الحالة',
    'selectgifttype': 'اختر نوع الهدية',
    'gift': 'الهديا',
    'giftlistpage': 'صفحة قائمة الهدايا',
    'uploadcitizenaffairdocuments': 'تحميل المستندات الخاصة بشؤون المواطنين',
    'fileuploadsuccess': 'تم رفع الملف بنجاح',
    'digitalsignature': 'التوقيع الالكتروني',
    'legalsubmittedby': 'مقدم من',
    'leavedoaofficedepartment': 'تفويض (مكتب / إدارة)',
    'salarycertificatecardtitle': 'طلبات شهادة الراتب',
    'experiencecertificatecardtitle': 'طلبات شهادة الخبرة',
    'newbabyadditioncardtitle': 'طلبات إضافة طفل جديد',
    'profiletitle': 'اللقب',

    'taskassignsuccessmsg': 'AR-dutytaskassignedsuccessfully',
    'more': 'المزيد',
    'extensionnumber': 'رقم التحويلة',
    'nobalanceleavedesc': 'عذراً، إن رصيد الإجازات السنوية الخاص بك لا يسمح بتقديم هذا الطلب. الرجاء التواصل مع شؤون الموارد البشرية​',
    'annualleave': 'إجازة سنوية',
    'otherleavetype': 'أنواع إجازات أخرى',
    'selectleavetype': 'اختر نوع الإجازة المطلوبة',
    'newbalanceleave': 'رصيد الإجازات المتبقي',
    'select': 'اختر',
    'selectall': 'إختيار الكل',
    'eventlist': 'قائمة الأحداث/ الفعاليات',
    'vehiclemgmt': 'إدارة المركبات',
    'vehicledocuments': 'الوثائق الخاصة بإدارة المركبات',
    'issuedagainstdepartment': 'مسجلة ضد - المكتب/القسم',
    'issuedagainstofficedepartment': 'تسجيل مخالفة مرورية على مكتب / إدارة',
    'issuedagainstname': 'مسجلة ضد - اسم الموظف',
    'finedatefrom': 'تاريخ المخالفة - من',
    'finedateto': 'تاريخ المخالفة - إلى',
    'finedetail': 'تفاصيل المخالفة',
    'platenumber': 'رقم اللوحة',
    'vehiclemodel': 'موديل المركبة',
    'finemgmt': 'إدارة المخالفات المرورية',
    'finenumber': 'رقم المخالفة',
    'finedescription': 'وصف المخالفة',
    'blackpoints': 'النقاط السوداء',
    'time': 'الوقت',
    'sendremainder': 'إرسال تذكير',
    'remindersentsuccessfully': 'تم إرسال التذكير بنجاح',
    'to': 'إلى',
    'cc': 'نسخة ل',
    'remainderdepartment': 'المكتب/ القسم',
    'remaindername': 'الإسم',
    'enterplatenumber': 'أدخل رقم اللوحة',
    'createvehiclerequest': 'إنشاء طلب سيارة',
    'requestor': 'صاحب الطلب',
    'circular': 'التعاميم',
    'vehiclereleaseconfirmation': 'تأكيد إرسال المركبة',
    'release': 'إنطلاق/ تسليم',
    'vehiclereturnconfirmation': 'تأكيد عودة المركبة',
    'vehiclerequestcreation': 'إنشاء طلب سيارة',
    'return': 'إرجاع',
    'tempcarwithdriver': 'سيارة مؤقتة مع سائق',
    'tempcarwithoutdriver': 'سيارة مؤقتة بدون سائق',
    'permanantcar': 'سيارة دائمة',
    'requestdatetime': 'تاريخ ووقت الطلب ',
    'drivername': 'اسم السائق/ المستخدم',
    'managedriver': 'إدارة السائقين',
    'managedrivers': 'إدارة السائقين',
    'listofallrrcemployees': 'قائمة بجميع موظفي الديوان',
    'drivers': 'السائقين',
    'driverlist': 'قائمة السائقين',
    'mobilenumber': 'رقم الهاتف المحمول',
    'numberofhourstobeadded': 'عدد الساعات المراد إضافتها',
    'compensateextrahours': 'تعويض ساعات اضافية',
    'numberofhourstobededucted': 'عدد الساعات المراد خصمها/ تعويضها',
    'compensate': 'تعويض',
    'tobedrivenbydepart': 'للاستخدام بواسطة - مكتب/ قسم',
    'tobedrivenbydriver': 'سيتم قيادتها بواسطة - اسم المستخدم',
    'triptype': 'نوع الرحلة',
    'plsspeicifyifothers': "الرجاء التحديد",
    'tripperiodfrom': 'تاريخ ووقت بداية الرحلة',
    'tripperiodto': 'تاريخ ووقت نهاية الرحلة',
    'copassengerdepar': 'مكتب / إدارة المرافقون',
    'copassengername': 'أسماء المرافقون',
    'copassengers': 'المسافرون المرافقون',
    'thisonthesameperiodfromandsamecity': 'الرحلات الأخرى المنطلقة من نفس المدينة وبنفس الوقت',
    'othertripsassignedtothedriveronthesameday': 'الرحلات الأخرى المسندة للسائق في نفس اليوم',
    'vehicleapproverdepartment': 'موافقة مكتب/ قسم',
    'vehicleapprovername': 'الموافقة من قبل',

    'memoredirectsuccessfully': 'تم إعادة التوجيه بنجاح',
    'incomingletterredirectsuccessfully': 'تمت اعادة توجيه الكتاب الوارد بنجاح',
    'outgoingletterredirectsuccessfully': 'تمت اعادة توجيه الكتاب الصادر بنجاح',

    'logintitle': 'تسجيل الدخول',
    'loginusername': 'إسم المستخدم',
    'loginuserplaceholder': 'الرجاء إدخال إسم المستخدم',
    'loginpassplaceholder': 'الرجاء إدخال كلمة المرور',
    'loginpassword': 'كلمة المرور',
    'loginbottom': 'الدخول',
    'loginsmartsystem': 'النظام الذكي',
    'loginStatement': "ديوان ممثل الحاكم - منطقة الظفرة",
    'documentwillexpiresoon': 'ستنتهي صلاحية أحد المستندات قريباً',
    'expireddocument': 'هناك مستند منتهي الصلاحية',
    'nextservicetyre': 'يجب إجراء الصيانة الدورية / تغيير الإطارات قريباً',
    'downloadasexcel': 'قم بتنزيل الملف كـملف إكسل',
    'platecolour': 'لون اللوحة ',
    'contractenddate': 'تاريخ انتهاء العقد',
    'vehicleregistrationexpiry': 'انتهاء صلاحية تسجيل المركبة',
    'nextserviceslashtyrechange': 'الصيانة القادمة / تغيير الإطارات',
    'usernamepwderr': 'إما أن اسم المستخدم الذي أدخلته غير صحيح أو أن كلمة المرور غير صحيحة، نرجو منك المحاولة مجدداً',
    'balanceextrahours': 'رصيد الساعات الإضافية',
    'addextrahours': 'إضافة ساعات اضافية',
    'addcompensiatehours': 'Add Compensiate Hours',
    'extrahoursreport': 'تقرير الساعات الإضافية',
    'extrahourreqmsg': ' تم بنحاح تسجيل ساعات العمل الإضافية',
    'compensatehourreqmsg': 'تم تعويض الساعات الإضافية بنجاح',
    'extrahours': 'الساعات الاضافية',
    'notifications': 'إشعارات',
    'notificationdetails': 'تفصيل الإشعار',
    'markallasread': 'تحديد الكل كمقروء',
    'deleted': 'محذوف',
    'mentioned': 'Mentioned',
    'vechilerequestsubmit': 'تم تقديم طلب المركبة بنجاح',
    'vehiclerequestapproval': 'الموافقة على طلب المركبة',
    'vehiclerequestview': 'عرض طلب المركبة',
    'vehiclecreation': 'إضافة مركبة',
    'vehicleview': 'عرض تفاصيل المركبة',
    'managevehiclecreatereqmsg': 'تم تسجيل تفاصيل المركبة بنجاح',
    'managevehicleupdatereqmsg': 'تم تحديث تفاصيل المركبة بنجاح',
    'temporary': 'مركبة مؤقتة',
    'logaservice': 'تسجيل صيانة دورية',
    'logatyrechange': 'تسجيل تغيير إطارات',
    'logafine': 'تسجيل مخالفة',
    'contractstartdate': 'مدة العقد (بالسنوات)',
    'departmentslashoffice': 'المكتب/ الإدارة',
    'nameoftheuser': 'إسم المستخدم',
    'yearofmanufacture': 'سنة الصنع',
    'addrentacarcompany': 'إضافة شركة تأجير السيارات',
    'rentacarcompany': 'شركة تأجير السيارات',
    'rentacarcompanymgmt': 'إدارة شركات تأجير السيارات',
    'companyname': 'اسم الشركة',
    'createddate': 'تاريخ الإنشاء',
    'contactnumber': 'رقم الاتصال',
    'contractnumber': 'رقم العقد',
    'contractduration': '(بالسنوات)مدة العقد',
    'vehivleregistrationnumber': 'رقم تسجيل المركبة -الملكية',
    'nextservice': 'موعد خدمة الصيانة التالي',
    'tyrechange': 'تغيير الاطارات',
    'managevehicles': 'إدارة المركبات',
    'vehicle': 'المركبة',
    'currentmileage': 'قراءة العداد الحالية',
    'nextmileage': 'الموعد التالي (العداد)',
    'currentmileageshouldbehigherthanlastmileage': 'الرجاء إدخال قيمة صحيحة، ملاحظة: يجب أن تكون قراءة العداد الحالية أكبر من قراءة العداد السابقة',
    'vehiclereqtriptimevalidationmsg': 'الرجاء إختيار قيمة صحيحة، ملاحظة: يجب أن يكون وقت انطلاق الرحلة قبل وقت الوصول',
    'vehiclerequestreturnconfirm': 'تم تأكيد نموذج إعادة المركبة بنجاح',
    'vehiclerequestreleased': 'تم تسليم/ إرسال المركبة بنجاح',
    'vehiclerequestreturn': 'تم تسجيل عودة المركبة بنجاح',
    'vehiclerequestreleaseconfirm': 'تم تأكيد نموذج تسليم المركبة بنجاح',
    'vehiclerequestapprove': 'تمت الموافقة على طلب المركبة بنجاح',
    'vehiclerequestreject': 'تم رفض طلب المركبة بنجاح',
    'vehiclerequestClose': 'تم إغلاق طلب المركبة بنجاح',
    'vehiclereqeustcancel': 'تم إلغاء طلب المركبة بنجاح',
    'vehiclerequestassignmsg': 'تم إسناد الرحلة لسائق بنجاح',
    'sendtorequestorconfirmation': 'الإرسال لصاحب الطلب للتأكيد',
    'lastmileagereading': 'قراءة العداد الأخيرة',
    'currentmileagereading': 'قراءة العداد الحالية',
    'releaselocation': 'مكان إنطلاق المركبة',
    'returnlocation': 'موقع اللإستلام',
    'carissues': 'مشاكل المركبة',
    'confirm': 'تأكيد',
    'isitalternativevehicle?': 'هل هي مركبة بديلة؟',
    'alternativevehicle': 'مركبة بديلة؟',
    'vehiclemake': 'ماركة المركبة',
    'vehiclename': 'موديل المركبة',
    'releasedatetime': 'تاريخ ووقت الإنطلاق',
    'vehicleissues': 'مشاكل المركبة الظاهرة',
    'plsspecifyyes': 'يرجى التحديد (إذا كانت الإجابة بنعم)',
    'personalbelonging': 'الأغراض الشخصية',
    'returndatetime': 'تاريخ ووقت العودة',
    'vehiclereturnconfirmationtitle': 'تأكيد عودة المركبة',
    'vehiclereleaseconfirmationtitle': 'تأكيد إرسال المركبة',
    'requestortype': 'نوع الطلب',
    'releaseform': 'نموذج تسليم المركبة',
    'vehiclereturnform': 'نموذج إرجاع المركبة',
    'assigntrip': 'إسناد طلب الرحلة لسائق',
    'citizenaffairservices': 'خدمات شؤون المواطنين',
    'maintenanceservices': 'خدمات الصيانة',
    'hrservices': 'خدمات شؤون الموظفين',
    'itservices': 'خدمات تقنية المعلومات',
    'carcompanyupdatedsuccessfull': 'شركة لتأجير السيارات تم تحديثها بنجاح',
    'carcompanycreatedsuccessfull': 'شركة لتأجير السيارات تم إنشاؤها بنجاح',
    'carcompanydeletedsuccessfull': 'شركة لتأجير السيارات المحذوفة بنجاح',
    'newvehicle': 'إضافة سيارة جديدة',
    'tripdatefrom': 'تاريخ بدء الرحلة',
    'tripdateto': 'تاريخ إنتهاء الرحلة',
    'vechilerequests': 'طلبات المركبات',
    'rentedcarcompaniesmanagement': 'إدارة شركات استئجار السيارات',
    'rentacarcompaniesmanagement': ' إدارة شركات استئجار السيارات',
    'finemanagement': 'إدارة المخالفات المرورية',
    'finedeletedmsg': 'تم حذف المخالفة بنجاح',
    'fineupdatedmsg': 'تم تحديث المخالفة بنجاح',
    'finesubmittedmsg': 'تم تسجيل المخالفة بنجاح',
    'VehicleManagement': 'إدارة المركبات',
    'madinatzayed': 'مدينة زايد',
    'abhudabhi': 'أبو ظبي',
    'servicehistory': 'سجل خدمات الصيانة الدورية',
    'servicetype': 'نوع الخدمة',
    'km': 'كم',
    'servicelog': 'سجلات الخدمة والصيانة',
    'releaseconfirmed': 'تم تأكيد الإستلام ',
    'released': 'تم التسليم/ الإرسال',
    'returned': 'تمت الإعادة ',
    'returnconfirmed': 'تم تأكيد إعادة المركبة ',
    'releaserejected': 'تم رفض إستلام المركبة',
    'finesubmitted': 'تم تسجيل مخالفة ',
    'finereminded': 'تم إرسال تذكير بمخالفة مرورية ',
    'vehiclefine': 'مخالفة مرورية',
    'drivermanagement': 'إدارة السائقين',
    'triptimefrom': 'وقت إنطلاق الرحلة',
    'triptimeto': 'وقت العودة',
    'wrdwebsite': 'الموقع الإلكتروني',
    'service': 'صيانة',
    'graduationdate': 'تاريخ التخرج',
    'servicelogs': 'سجلات الخدمة والصيانة',
    'Certificateneedstobeuploaded':'يجب تحميل الشهادة ',
    'trainingreqattendencesavemsg':'تم تحميل إثبات الحضور بنجاح',
    'Certificateuploadedby':'تم تحميل الشهادة',
    'ProofOfAttendanceSubmittedBy':'تم تحميل إثبات الحضور بواسطة',
    'CircularApproved' : 'معتمد'
  }
}
